version: '3.5'

networks:
  user_bridge_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - user_bridge_network
    container_name: home-library
    environment:
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgr
    networks:
      - user_bridge_network
    hostname: db
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'